# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


pod ‘DistanceGetter’ , ‘~> 0.1’

target 'project4' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for project4

  target 'project4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'project4UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
